### ISSUE TITLE
Fix parser to handle transform card

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#10]
1. Open diab
2. Write `4 Legion's Landing // Adanto, the First Fort`
3. Search

Expected : 4 `Legion's Landing` and 4 `Adanto, the First Fort` cards.

Actual: nothing and a "boo" in console.

Solution: if name contains " // ", split it into two cards and flatten both into the list of card, then multiply each by the multiplier (i.e. `4`).

Bonus solution: Since `Adanto, the First Fort` is legendary, should we optimize the output by only adding one to the print ? So the expected would be 4 `Legion's Landing` and 1 `Adanto, the First Fort` cards only because the back card is legendary.

**Comment by birdmod** [comment]
About bonus solution, Legion's Landing (front side) is a legendary enchantment. Expected output should be **`1`** `Legion's Landing` and `1 Adanto, the First Fort` instead.
