### ISSUE TITLE
Add token

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#18]
Scryfall host token card. We should be able to find them from the api.

https://scryfall.com/sets?type=token

**Comment by birdmod** [comment]
This will be for additional/standalone token, which is cool. 
In fact, tokens added into a deck are not _always_ reachable. Example with the [angel warrior from Zendikar Rising tokens](https://scryfall.com/card/tznr/1/angel-warrior). 
When added to a Scryfall deck and then exported to a clipboard, it is displayed as
`1 Angel Warrior`
Unfortunately, querying on it results into [its best friend](https://scryfall.com/card/sth/24/warrior-angel), `Warrior angel`.

**Comment by aloisdg** [comment]
What if we query with the set i.e. `Warrior Angel (TZNR)`?

`1 Angel Warrior` should return the first scryfall result for "Angel Warrior" but `1 Angel Warrior (TZNR)`  should display the token. I don't think we support set right now though.

[Angel Warrior set:TZNR](https://scryfall.com/search?q=Angel+Warrior+set%3ATZNR&unique=cards&as=grid&order=name) vs [Angel Warrior](https://scryfall.com/search?q=Angel+Warrior)
