### ISSUE TITLE
Add an option to skip basic land

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#19]
When we netdeck to try new deck, it can be cool to skip all basic land.

**Comment by birdmod** [comment]
What do you call netdeck ? Is it copy-pasting a deck list description?

**Comment by aloisdg** [comment]
Yes. Netdecking is copy-pasting a deck list description:

> Any deck copied from the internet or a published tournament listing and changed to deal with the local metagame. The practice of using such decks is referred to as "netdecking". 

[List of Magic slang](https://mtg.gamepedia.com/List_of_Magic_slang)

**Comment by aloisdg** [comment]
@birdmod do you want to handle this one?

**Comment by aloisdg** [comment]
Decklist test:

```
1 Forest (ELD)
2 Mountain (CHK)
1 Island
1 Wastes
1 Swamp (TSP)
1 Plains
1 Deep Forest Hermit
```

**Comment by aloisdg** [comment]
![skipbasicland](https://user-images.githubusercontent.com/3449303/97559463-bfb97000-19dd-11eb-9422-f04bcf70566a.gif)
