### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#22]
Hello,

I dont like Diab as a name. How about renaming the project? How would you like to call it?
Any help is welcome!

Cheers,

**Comment by aloisdg** [comment]
Something about ink maybe? Why not mtgink.com?

* [Inkmoth Infusion](https://scryfall.com/card/5dn/25/blinkmoth-infusion)?
* [Inkfathom Proxy](https://scryfall.com/card/jud/36/cephalid-inkshrouder)? or just [inkfathom.com](https://scryfall.com/card/pca/97/inkfathom-witch)

Or ink -> octopus -> [Cephalid](https://scryfall.com/card/jud/36/cephalid-inkshrouder)? Cephalid Proxy?  I like the idea of Cephalid Proxy

If we want an alliteration [Creation Type](https://mtg.gamepedia.com/Creature_type):

- Pangolin
- Peasant
- Pegasus
- Pentavite
- Pest
- Phelddagrif
- Phoenix
- Pilot
- Pincher
- Pirate
- Plant
- Praetor
- Prism
- Processor

I like Pentavite Proxy, Phelddagrif Proxy and Praetor Proxy. Praetor Proxy is my favorite.

**Comment by aloisdg** [comment]
mtgpdf.com?

**Comment by aloisdg** [comment]
20 days later my favorite choices are:

- Inkfathom Proxy (inkfathom.com)
- Cephalid Proxy (cephalidproxy.com)
- MtG Ink (mtgink.com)

**Comment by birdmod** [comment]
Phelddagrif Proxy is funny and with the idea of helping others. From your choices, Inkfathom proxy is nice 🖨️ 🖨️ 🖨️
