### ISSUE TITLE
Add an option to print in black and white

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#25]
Hello,

If most printers can convert to black and white themselves, I think it would be nice to handle it our-self.
There are three steps: 

- Add an option to select between colors and Black & White. Colors should be the first and default options.
- Add a [CSS filter](https://stackoverflow.com/a/30250245) to switch the palette of each card in deck.
- Add a [function](https://stackoverflow.com/a/35180284) to transform the card in the canvas before printing.

Have fun

**Comment by birdmod** [comment]
When reading the [Card Imagery > Image Guidelines](https://scryfall.com/docs/api/images), one of them states:

> Do not blur, sharpen, desaturate, or color-shift card images.

It falls under color-shifting rule so it's not allowed 🚫

**Comment by aloisdg** [comment]
Alright. We could ask for precision in our case. I will still close this issue for now because most printer can to that after all and I prefer this solution to be printing friendly:  #17
