### ISSUE TITLE
Highlight the number of print available

### ISSUE THREAD

**Issue by KimClarisse** [aloisdg/diab#60]
**Is your feature request related to a problem? Please describe.**
It is not clear when using the switch print button, if it is working accordingly, when there is only one print available for a card.
It would be easier for the user to highlight the number of print available for a card, somewhere on the card. 

**Describe the solution you'd like**
Displaying the information in the form of a slowly vanishing block. Consisting of the current print number and the total number of print available for the card. Like that => Print 2/15 or Print 2*15 or else.

**Comment by aloisdg** [comment]
Nice idea! Here we go:

![walkprintwithcounter](https://user-images.githubusercontent.com/3449303/98159149-5dc8a100-1edc-11eb-9178-1d35f7848507.gif)

I may improve it later on.

@KimClarisse You can try it [here](https://deploy-preview-63--inkfathom.netlify.app/)

**Comment by KimClarisse** [comment]
Wow that was fast. Thank you, it fulfill its role completely.
