### ISSUE TITLE
Show what cards failed and were not displayed

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/diab#61]
example: https://inkfathom.netlify.app/?cards=1+Opt%0A1+Riverglide+Pathway+%2F%2F+Lavaglide+Pathway%0Aaloisdg&tokens=1+Squirrel+%28UND%29

Here we dont know that `aloisdg`  is not here.

**Comment by aloisdg** [comment]
desktop:

![image](https://user-images.githubusercontent.com/3449303/98117117-8e431780-1ea9-11eb-95fd-8d1e4a69f1a5.png)

mobile:

![image](https://user-images.githubusercontent.com/3449303/98117175-a155e780-1ea9-11eb-8304-2280db9dec46.png)


Current work. What do you think?

**Comment by aloisdg** [comment]
@KimClarisse @birdmod Is it better without the gradient?

![image](https://user-images.githubusercontent.com/3449303/98142943-ca39a500-1ec8-11eb-9ee0-a9bde9c0d4d9.png)

[Try it online](https://deploy-preview-62--inkfathom.netlify.app/)

**Comment by KimClarisse** [comment]
Well it's perfect as it is, you should leave it that way I think. Good job! Love the subtle shading.

**Comment by aloisdg** [comment]
Alright lets merge it!
