### ISSUE TITLE
Size default back to normal when selecting other cards and printing them

### ISSUE THREAD

**Issue by KimClarisse** [aloisdg/diab#78]
**Describe the bug**
just tried 'tiny' and it produces 5x5 card sheets now.
If you change the cards afterwards and 'print' another pdf the size defaults back to normal though (even with the setting still on tiny)

**To Reproduce**
load page with default card list.
Change squirrels to 21.
Click the magnifier to load the extra squirrels.
Set size to tiny. (The preview shrinks)
Click print. -> Get a pdf with a 5x5 grid.

Now change squirrels to 22 (or whatever)
Click the magnifier to load the change.
! Don't change the cardsize (the option is still on tiny on the dropdown)
Click the print button -> You get a pdf with a 3x3 grid even though tiny was selected, because you always have to select it after clicking the magnifier button for it to work.
**Expected behavior**

Copy Pasta of the bug reported by Kain Morgen on Discord, we thank you Kain !

**Comment by aloisdg** [comment]
the bug in gif:

![bug_configuration](https://user-images.githubusercontent.com/3449303/123537384-63a31900-d72f-11eb-933a-b249de224e9c.gif)

**Comment by aloisdg** [comment]
alright I have a working fix:

![fix_configuration](https://user-images.githubusercontent.com/3449303/123538031-ef6a7480-d732-11eb-85c4-fef2a22393bb.gif)

**Comment by aloisdg** [comment]
The fix can be tested: https://deploy-preview-80--inkfathom.netlify.app/
